### ISSUE TITLE
GPL3 prevents usage in enterprise software

### ISSUE THREAD

**Issue by jensborrmann** [jqassistant-contrib/jqassistant-java-ddd-plugin#3]
We would like to use your annotations, concepts and constraints in our applications. The chosen open source license is problematic for us. GPL3.0 would force us to open source our complete software (https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)).

This is due to the fact that the ddd annotations have to be used in production code.

Is there a chance for switching the license (or dual licensing) and use a more enterprise friendly license  such as LGPL or ASL?

**Comment by StephanPirnbaum** [comment]
Hi,

this is due to the dependency to Neo4J. With the upcoming 1.8 release, the annotations will be provided as a separate artifact with a more enterprise friendly license, so that they can be referenced as a maven dependency. 

Regarding the concepts and constraints: Since it’s a dependency for the jQAssistant maven plug-in, the license should be fine as those artifacts won’t be part of the delivery. 

Best,
Stephan

**Comment by jensborrmann** [comment]
Thanks for the fast reaction - that's very good news!

Is there already a scheduled release date for version 1.8?

**Comment by StephanPirnbaum** [comment]
Hi, the release will happen during the next days. I'll keep you posted.

**Comment by StephanPirnbaum** [comment]
We recently released version 1.8.0: 
https://search.maven.org/search?q=g:org.jqassistant.contrib.plugin%20AND%20a:jqassistant-java-ddd-*%20AND%20v:1.8.0

**Comment by jensborrmann** [comment]
Great news. Thanks a lot for this improvement.
